apiVersion: apps/v1
kind: Deployment
metadata:
  name: firebase-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firebase-auth
  template:
    metadata:
      labels:
        app: firebase-auth
    spec:
      containers:
      - name: firebase-auth-container
        image: firebase-auth-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
