apiVersion: v1
kind: Service
metadata:
  name: firebase-auth-service
spec:
  type: NodePort
  selector:
    app: firebase-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30036
